name: "TruffleHog Scan"
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  scan-secrets:
    docker:
      - image: trufflesecurity/trufflehog:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run:
        name: "Scan for secrets"
        # change --since-commit to match your default branch
        command: trufflehog git file://. --since-commit main --branch "${{github.ref_branch}}" --fail --only-verified

workflows:
  scan-secrets:
    jobs:
      - scan-secrets
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4
#       with:
#         fetch-depth: 0

#     - name: Secret Scanning
#       uses: trufflesecurity/trufflehog@main
#       with:
#         extra_args: --no-verification

    # - name: scan-push
    #   uses: trufflesecurity/trufflehog@main
    #   with:
    #     base: ""
    #     head: ${{ github.ref_branch }}
    #     extra_args: --results=verified,unknown