name: "TruffleHog Docker Scan"
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: trufflesecurity/trufflehog:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: test_keys

    
    # - name: Debug Branch
    #   run: |
    #     git config --global --add safe.directory WebGoat
    #     git log --oneline && ls -la

    - name: Secret Scanning
      run: |
        trufflehog git file://test_keys --no-verification
        